import { authService } from './AuthService';
import { CONFIG } from '../config';

export interface Customer {
    id: string;
    name: string;
    phone: string;
    address: string;
    email: string;
    gstin: string;
    customerType: 'Retail' | 'Wholesale';
    status: 'Active' | 'Inactive';
    totalPurchases: number;
    totalOrders: number;
    lastPurchaseDate: string;
    createdAt: string;
    updatedAt: string;
    branch?: string;
    createdBy?: string;
}

class CustomerService {
    private API_URL = `${CONFIG.API_BASE_URL}/customers`;

    async getAllCustomers(): Promise<Customer[]> {
        try {
            const response = await fetch(this.API_URL);
            if (!response.ok) throw new Error('Failed to fetch customers');
            return await response.json();
        } catch (error) {
            console.error('Error fetching customers:', error);
            return [];
        }
    }

    async getCustomerById(id: string): Promise<Customer | undefined> {
        try {
            const response = await fetch(`${this.API_URL}/${id}`);
            if (!response.ok) return undefined;
            return await response.json();
        } catch (error) {
            console.error('Error fetching customer:', error);
            return undefined;
        }
    }

    async addCustomer(customer: Omit<Customer, 'id' | 'createdAt' | 'updatedAt' | 'totalPurchases' | 'totalOrders' | 'lastPurchaseDate'>): Promise<Customer | null> {
        try {
            const user = authService.getCurrentUser();
            const newCustomer = {
                ...customer,
                // id: Generated by backend (VKCxxxx)
                branch: user?.branch || 'Main',
                createdBy: user?.username || 'System'
            };

            const response = await fetch(this.API_URL, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(newCustomer)
            });

            if (!response.ok) {
                const errorData = await response.json().catch(() => ({ error: 'Unknown Error' }));
                throw new Error(errorData.error || errorData.details || 'Failed to create customer');
            }
            return await response.json();
        } catch (error) {
            console.error('Error adding customer:', error);
            return null;
        }
    }

    async updateCustomer(id: string, updates: Partial<Customer>): Promise<Customer | null> {
        try {
            const response = await fetch(`${this.API_URL}/${id}`, {
                method: 'PUT',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(updates)
            });

            if (!response.ok) throw new Error('Failed to update customer');
            return await response.json();
        } catch (error) {
            console.error('Error updating customer:', error);
            return null;
        }
    }

    async deleteCustomer(id: string): Promise<boolean> {
        try {
            const response = await fetch(`${this.API_URL}/${id}`, {
                method: 'DELETE'
            });
            return response.ok;
        } catch (error) {
            console.error('Error deleting customer:', error);
            return false;
        }
    }
}

export const customerService = new CustomerService();
